//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Data.Entities
{
    public partial class User : IValidatableObject
    {
        public User()
        {
            this.UserApplications = new HashSet<ApplicationUser>();
        }
    
        public long Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<ApplicationUser> UserApplications { get; set; }
    
    	partial void CustomValidate(ValidationContext validationContext, ref IEnumerable<ValidationResult> validationResults);
    	private IEnumerable<ValidationResult> CustomValidateWrapper(ValidationContext validationContext)
        {
    		var results = new List<ValidationResult>();
    		var enumerable = results as IEnumerable<ValidationResult>;
            CustomValidate(validationContext, ref enumerable);
    		return results;
    	}
    
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
    		return CustomValidateWrapper(validationContext);
        }
    }
    
}
