
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace Data.Migrations
{
    /// <remarks>
    /// To add new migration run the following script
    /// Add-Migration ${migrationName} -ProjectName "${projectName}" -StartUpProjectName "${projectName}" -ConfigurationTypeName "Data.Migrations.DbMigrationsConfiguration" -ConnectionString ${connectionString} -ConnectionProviderName "System.Data.SqlClient"
    /// Add-Migration InitialCreate -ProjectName "Data" -StartUpProjectName "Data" -ConfigurationTypeName "Data.Migrations.DbMigrationsConfiguration" -ConnectionString "Server=localhost;Database=EF;Trusted_Connection=True;" -ConnectionProviderName "System.Data.SqlClient"
    /// </remarks>
    public sealed class DbMigrationsConfiguration : DbMigrationsConfiguration<DatabaseContext>
    {
        public DbMigrationsConfiguration()
        {
            var dbContextType = typeof(DatabaseContext);
    
            AutomaticMigrationsEnabled = true;
            MigrationsAssembly = dbContextType.Assembly;
            MigrationsNamespace = "Data.Migrations";
            MigrationsDirectory = "Migrations";
            ContextType = dbContextType;
        }
    
        protected override void Seed(DatabaseContext context)
        {
            base.Seed(context);
        }
    
        public static void UpdateSchema(string connectionString)
        {
            var migrator = new MigrateDatabaseToLatestVersion<DatabaseContext, DbMigrationsConfiguration>();
    
            using (var context = new DatabaseContext(connectionString))
            {
                migrator.InitializeDatabase(context);
            }
        }
    }
}
