//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using Data.Entities;

namespace Data.Repositories
{
    public partial class TestRepository : IDbSet<Test>
    {
        private readonly DbSet<Test> _dbSet;
    
        internal TestRepository(DbSet<Test> dbSet)
        {
    		_dbSet = dbSet;
        }
        
    	public Test Add(Test entity)
    	{
     		return _dbSet.Add(entity);
    	}
    
    	public Test Attach(Test entity)
    	{
     		return _dbSet.Attach(entity);
    	}
    
    	public Test Create()
    	{
     		return _dbSet.Create();
    	}
    
        TDerivedEntity IDbSet<Test>.Create<TDerivedEntity>()
        {
            return _dbSet.Create<TDerivedEntity>();
        }
    
    	public Test Find(params object[] keyValues)
    	{
     		return _dbSet.Find(keyValues);
    	}
    
    	public System.Collections.ObjectModel.ObservableCollection<Test> Local
    	{
    		get { return _dbSet.Local; }
    	}
    
    	public Test Remove(Test entity)
    	{
    		return _dbSet.Remove(entity);
    	}
    
        public Type ElementType
        {
            get { return ((IQueryable)_dbSet).ElementType; }
        }
    
        public System.Linq.Expressions.Expression Expression
        {
            get { return ((IQueryable)_dbSet).Expression; }
        }
    
        public System.Linq.IQueryProvider Provider
        {
            get { return ((IQueryable)_dbSet).Provider; }
        }
    
        public IEnumerator<Test> GetEnumerator()
        {
            return ((IEnumerable<Test>) _dbSet).GetEnumerator();
        }
    
        IEnumerator IEnumerable.GetEnumerator()
        {
            return ((IEnumerable) _dbSet).GetEnumerator();
        }
    }
    
}
