//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using Data.Entities;

namespace Data.Repositories
{
    public partial class UserRepository : IDbSet<User>
    {
        private readonly DbSet<User> _dbSet;
    
        internal UserRepository(DbSet<User> dbSet)
        {
    		_dbSet = dbSet;
        }
        
    	public User Add(User entity)
    	{
     		return _dbSet.Add(entity);
    	}
    
    	public User Attach(User entity)
    	{
     		return _dbSet.Attach(entity);
    	}
    
    	public User Create()
    	{
     		return _dbSet.Create();
    	}
    
        TDerivedEntity IDbSet<User>.Create<TDerivedEntity>()
        {
            return _dbSet.Create<TDerivedEntity>();
        }
    
    	public User Find(params object[] keyValues)
    	{
     		return _dbSet.Find(keyValues);
    	}
    
    	public System.Collections.ObjectModel.ObservableCollection<User> Local
    	{
    		get { return _dbSet.Local; }
    	}
    
    	public User Remove(User entity)
    	{
    		return _dbSet.Remove(entity);
    	}
    
        public Type ElementType
        {
            get { return ((IQueryable)_dbSet).ElementType; }
        }
    
        public System.Linq.Expressions.Expression Expression
        {
            get { return ((IQueryable)_dbSet).Expression; }
        }
    
        public System.Linq.IQueryProvider Provider
        {
            get { return ((IQueryable)_dbSet).Provider; }
        }
    
        public IEnumerator<User> GetEnumerator()
        {
            return ((IEnumerable<User>) _dbSet).GetEnumerator();
        }
    
        IEnumerator IEnumerable.GetEnumerator()
        {
            return ((IEnumerable) _dbSet).GetEnumerator();
        }
    }
    
}
