//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using Data.Entities;

namespace Data.Configurations
{
    internal partial class ApplicationConfiguration : EntityTypeConfiguration<Application>
    {
    	partial void CustomConfiguration();
    
        public ApplicationConfiguration()
        {
    		this.HasKey(t => t.Id);
    		this.Property(t => t.Name).IsRequired().HasMaxLength(256);
    		this.Property(t => t.DisplayName).IsRequired().HasMaxLength(512);
    		this.Property(t => t.Description).IsRequired();
    		CustomConfiguration();
        }
    }
}
