//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using Data.Entities;

namespace Data.Configurations
{
    internal partial class ApplicationUserConfiguration : EntityTypeConfiguration<ApplicationUser>
    {
    	partial void CustomConfiguration();
    
        public ApplicationUserConfiguration()
        {
    		this.HasKey(t => t.Id);
    		this.HasRequired(t => t.Application).WithMany(t => t.ApplicationUsers).HasForeignKey(d => d.ApplicationId);
    		this.HasRequired(t => t.User).WithMany(t => t.UserApplications).HasForeignKey(d => d.UserId);
    		CustomConfiguration();
        }
    }
}
