//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using Data.Entities;

namespace Data.Configurations
{
    internal partial class TestConfiguration : EntityTypeConfiguration<Test>
    {
    	partial void CustomConfiguration();
    
        public TestConfiguration()
        {
    		this.ToTable("Tests");
    		this.HasKey(t => t.Id);
    		this.Property(t => t.Balance).HasPrecision(18, 15);
    		this.Property(t => t.RowVersion).IsRowVersion();
    		CustomConfiguration();
        }
    }
}
