//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using Data.Entities;

namespace Data.Configurations
{
    internal partial class UserConfiguration : EntityTypeConfiguration<User>
    {
    	partial void CustomConfiguration();
    
        public UserConfiguration()
        {
    		this.ToTable("Users");
    		this.HasKey(t => t.Id);
    		this.Property(t => t.Username).IsRequired().HasMaxLength(256);
    		this.Property(t => t.Email).IsRequired().HasMaxLength(256);
    		CustomConfiguration();
        }
    }
}
